{
 "title": "Systems Stats",
 "description": "From Telegraf -> InfluxDB",
 "tags": [ "collectd" ],
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "host",
    "query": "SHOW TAG VALUES WITH KEY = \"host\""
   }
  ]
 },
 "panels": [
  {
   "title": "Uptime",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 8, "x": 0, "y": 0 },
   "format": "dtdurations",
   "valueName": "current",
   "targets": [
    {
     "measurement": "system",
     "select": [
      [
       { "params": [ "uptime_format" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" }
     ]
    }
   ]
  },
  {
   "title": "Users",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 8, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "measurement": "system",
     "select": [
      [
       { "params": [ "n_users" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" }
     ]
    }
   ]
  },
  {
   "title": "Load (Long)",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 12, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "measurement": "system",
     "select": [
      [
       { "params": [ "load15" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" }
     ]
    }
   ]
  },
  {
   "title": "Load (Mid)",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 16, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "measurement": "system",
     "select": [
      [
       { "params": [ "load5" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" }
     ]
    }
   ]
  },
  {
   "title": "Load (Short)",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 20, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "measurement": "system",
     "select": [
      [
       { "params": [ "load1" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" }
     ]
    }
   ]
  },
  {
   "title": "$host CPU",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 3 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "alias": "$col",
     "groupBy": [
      { "params": [ "cpu" ], "type": "tag" }
     ],
     "measurement": "cpu",
     "query": "SELECT mean(\"value\") FROM \"telegraf\".\"autogen\" WHERE $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "usage_system" ], "type": "field" }
      ],
      [
       { "params": [ "usage_user" ], "type": "field" }
      ],
      [
       { "params": [ "usage_iowait" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" },
      { "condition": "AND", "key": "cpu", "operator": "=", "value": "cpu-total" }
     ]
    }
   ]
  },
  {
   "title": "$host Swap",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 3 },
   "yaxes": [
    { "format": "decbits" }
   ],
   "targets": [
    {
     "measurement": "swap",
     "query": "SELECT mean(\"value\") FROM \"autogen\".\"memory_value\" WHERE (\"host\"  =~ /^$host$/ AND (\"type_instance\" = 'cached' OR \"type_instance\" = 'free' OR \"type_instance\" = 'buffered' OR \"type_instance\" = 'used')) AND $timeFilter GROUP BY time($__interval), \"type_instance\" fill(linear)",
     "select": [
      [
       { "params": [ "free" ], "type": "field" }
      ],
      [
       { "params": [ "used" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" }
     ]
    }
   ]
  },
  {
   "title": "$host Processes",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 12 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "alias": "$col",
     "groupBy": [
      { "params": [ "type_instance" ], "type": "tag" }
     ],
     "measurement": "processes",
     "query": "SELECT mean(\"value\") FROM \"autogen\".\"processes_value\" WHERE (\"host\"  =~ /^$host$/ AND \"type\" = 'fork_rate') AND $timeFilter GROUP BY time(1s), \"type_instance\" fill(linear)",
     "select": [
      [
       { "params": [ "*" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" }
     ]
    }
   ]
  },
  {
   "title": "$host Read IOPs",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 19 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "alias": "$tag_name",
     "groupBy": [
      { "params": [ "name" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "diskio",
     "query": "SELECT mean(\"value\") FROM \"autogen\".\"processes_value\" WHERE (\"host\"  =~ /^$host$/ AND \"type\" = 'fork_rate') AND $timeFilter GROUP BY time(1s), \"type_instance\" fill(linear)",
     "select": [
      [
       { "params": [ "read_bytes" ], "type": "field" },
       { "params": [ "1s" ], "type": "derivative" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" }
     ]
    }
   ]
  },
  {
   "title": "$host Write IOPs",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 19 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "$tag_name",
     "groupBy": [
      { "params": [ "name" ], "type": "tag" }
     ],
     "measurement": "diskio",
     "query": "SELECT mean(\"value\") FROM \"autogen\".\"processes_value\" WHERE (\"host\"  =~ /^$host$/ AND \"type\" = 'fork_rate') AND $timeFilter GROUP BY time(1s), \"type_instance\" fill(linear)",
     "select": [
      [
       { "params": [ "writes" ], "type": "field" },
       { "params": [ "1s" ], "type": "derivative" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" }
     ]
    }
   ]
  },
  {
   "title": "$host Disk Usage",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 19 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "device" ], "type": "tag" }
     ],
     "measurement": "disk",
     "query": "SELECT mean(\"value\") FROM \"autogen\".\"processes_value\" WHERE (\"host\"  =~ /^$host$/ AND \"type\" = 'fork_rate') AND $timeFilter GROUP BY time(1s), \"type_instance\" fill(linear)",
     "select": [
      [
       { "params": [ "used_percent" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" },
      { "condition": "AND", "key": "device", "operator": "!=", "value": "devfs" }
     ]
    }
   ]
  },
  {
   "title": "$host Network Traffic/sec",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 25 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "alias": "$tag_interface Rx",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "interface" ], "type": "tag" }
     ],
     "measurement": "net",
     "query": "SELECT mean(\"value\") FROM \"autogen\".\"processes_value\" WHERE (\"host\"  =~ /^$host$/ AND \"type\" = 'fork_rate') AND $timeFilter GROUP BY time(1s), \"type_instance\" fill(linear)",
     "select": [
      [
       { "params": [ "bytes_recv" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "1s" ], "type": "derivative" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" }
     ]
    },
    {
     "alias": "$tag_interface Tx",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "interface" ], "type": "tag" }
     ],
     "measurement": "net",
     "query": "SELECT mean(\"value\") FROM \"autogen\".\"processes_value\" WHERE (\"host\"  =~ /^$host$/ AND \"type\" = 'fork_rate') AND $timeFilter GROUP BY time(1s), \"type_instance\" fill(linear)",
     "select": [
      [
       { "params": [ "bytes_sent" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "1s" ], "type": "derivative" },
       { "params": [ "*-1" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" }
     ]
    }
   ]
  },
  {
   "title": "$host Network Errors/sec",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 25 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "alias": "$tag_interface Rx",
     "groupBy": [
      { "params": [ "instance" ], "type": "tag" },
      { "params": [ "type" ], "type": "tag" },
      { "params": [ "interface" ], "type": "tag" }
     ],
     "measurement": "net",
     "query": "SELECT mean(\"value\") FROM \"autogen\".\"processes_value\" WHERE (\"host\"  =~ /^$host$/ AND \"type\" = 'fork_rate') AND $timeFilter GROUP BY time(1s), \"type_instance\" fill(linear)",
     "select": [
      [
       { "params": [ "err_in" ], "type": "field" },
       { "params": [ "1s" ], "type": "derivative" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" }
     ]
    },
    {
     "alias": "$tag_interface Tx",
     "groupBy": [
      { "params": [ "instance" ], "type": "tag" },
      { "params": [ "type" ], "type": "tag" },
      { "params": [ "interface" ], "type": "tag" }
     ],
     "measurement": "net",
     "query": "SELECT mean(\"value\") FROM \"autogen\".\"processes_value\" WHERE (\"host\"  =~ /^$host$/ AND \"type\" = 'fork_rate') AND $timeFilter GROUP BY time(1s), \"type_instance\" fill(linear)",
     "select": [
      [
       { "params": [ "err_out" ], "type": "field" },
       { "params": [ "1s" ], "type": "derivative" },
       { "params": [ "*-1" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" }
     ]
    }
   ]
  },
  {
   "title": "$host Network Packets/sec",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 25 },
   "yaxes": [
    { "format": "pps" }
   ],
   "targets": [
    {
     "alias": "$tag_interface Rx",
     "groupBy": [
      { "params": [ "instance" ], "type": "tag" },
      { "params": [ "type" ], "type": "tag" },
      { "params": [ "interface" ], "type": "tag" }
     ],
     "measurement": "net",
     "query": "SELECT mean(\"value\") FROM \"autogen\".\"processes_value\" WHERE (\"host\"  =~ /^$host$/ AND \"type\" = 'fork_rate') AND $timeFilter GROUP BY time(1s), \"type_instance\" fill(linear)",
     "select": [
      [
       { "params": [ "packets_recv" ], "type": "field" },
       { "params": [ "1s" ], "type": "derivative" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" }
     ]
    },
    {
     "alias": "$tag_interface Tx",
     "groupBy": [
      { "params": [ "instance" ], "type": "tag" },
      { "params": [ "type" ], "type": "tag" },
      { "params": [ "interface" ], "type": "tag" }
     ],
     "measurement": "net",
     "query": "SELECT mean(\"value\") FROM \"autogen\".\"processes_value\" WHERE (\"host\"  =~ /^$host$/ AND \"type\" = 'fork_rate') AND $timeFilter GROUP BY time(1s), \"type_instance\" fill(linear)",
     "select": [
      [
       { "params": [ "packets_sent" ], "type": "field" },
       { "params": [ "1s" ], "type": "derivative" },
       { "params": [ "*-1" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" }
     ]
    }
   ]
  },
  {
   "title": "$host Temperatures",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 31 },
   "yaxes": [
    { "format": "celsius" }
   ],
   "targets": [
    {
     "alias": "$tag_feature",
     "groupBy": [
      { "params": [ "feature" ], "type": "tag" }
     ],
     "measurement": "sensors",
     "select": [
      [
       { "params": [ "temp_input" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" },
      { "condition": "AND", "key": "chip", "operator": "!=", "value": "sysctl" }
     ]
    },
    {
     "alias": "$tag_feature",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "feature" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "sensors",
     "select": [
      [
       { "params": [ "temp_input" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" },
      { "condition": "AND", "key": "chip", "operator": "=", "value": "sysctl" }
     ]
    }
   ]
  }
 ]
}