{
 "title": "CollectD InfluxDB",
 "tags": [ "collectd" ],
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "host",
    "query": "SHOW TAG VALUES WITH KEY = \"host\""
   }
  ]
 },
 "panels": [
  {
   "title": "Uptime",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 0 },
   "format": "dtdurations",
   "valueName": "current",
   "targets": [
    {
     "measurement": "uptime_value",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" }
     ]
    }
   ]
  },
  {
   "title": "Entropy",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 4, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "measurement": "entropy_value",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" }
     ]
    }
   ]
  },
  {
   "title": "Users",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 8, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "measurement": "users_value",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" }
     ]
    }
   ]
  },
  {
   "title": "Load (Long)",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 12, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "measurement": "load_longterm",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" }
     ]
    }
   ]
  },
  {
   "title": "Load (Mid)",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 16, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "measurement": "load_midterm",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" }
     ]
    }
   ]
  },
  {
   "title": "Load (Short)",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 20, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "measurement": "load_shortterm",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" }
     ]
    }
   ]
  },
  {
   "title": "$host CPU",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 3 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "alias": "$tag_type_instance",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "type_instance" ], "type": "tag" },
      { "params": [ "instance" ], "type": "tag" },
      { "params": [ "linear" ], "type": "fill" }
     ],
     "measurement": "cpu_value",
     "query": "SELECT mean(\"value\") FROM \"autogen\".\"cpu_value\" WHERE (\"host\"  =~ /^$host$/ AND (\"type_instance\" = 'system' OR \"type_instance\" = 'wait' OR \"type_instance\" = 'user')) AND $timeFilter GROUP BY time($__interval), \"type_instance\" fill(linear)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "starbug1" },
      { "condition": "AND", "key": "and", "operator": "=", "value": "select tag value" }
     ]
    }
   ]
  },
  {
   "title": "$host Memory",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 3 },
   "yaxes": [
    { "format": "decbits" }
   ],
   "targets": [
    {
     "alias": "$tag_type_instance",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT mean(\"value\") FROM \"autogen\".\"memory_value\" WHERE (\"host\"  =~ /^$host$/ AND (\"type_instance\" = 'cached' OR \"type_instance\" = 'free' OR \"type_instance\" = 'buffered' OR \"type_instance\" = 'used')) AND $timeFilter GROUP BY time($__interval), \"type_instance\" fill(linear)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "$host Load",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 12 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "alias": "$tag_type_instance",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT mean(\"value\") FROM \"autogen\".\"load_shortterm\" WHERE (\"host\"  =~ /^$host$/) AND $timeFilter GROUP BY time($__interval), \"type_instance\" fill(linear)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "$host Process Fork/sec",
   "type": "graph",
   "gridPos": { "h": 9, "w": 4, "x": 8, "y": 12 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "alias": "$host Fork/s",
     "measurement": "processes_value",
     "query": "SELECT mean(\"value\") FROM \"autogen\".\"processes_value\" WHERE (\"host\"  =~ /^$host$/ AND \"type\" = 'fork_rate') AND $timeFilter GROUP BY time(1s), \"type_instance\" fill(linear)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       { "params": [ "1s" ], "type": "derivative" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" },
      { "condition": "AND", "key": "type", "operator": "=", "value": "fork_rate" }
     ]
    }
   ]
  },
  {
   "title": "$host Processes",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 12 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "alias": "$tag_type_instance",
     "groupBy": [
      { "params": [ "type_instance" ], "type": "tag" }
     ],
     "measurement": "processes_value",
     "query": "SELECT mean(\"value\") FROM \"autogen\".\"processes_value\" WHERE (\"host\"  =~ /^$host$/ AND \"type\" = 'fork_rate') AND $timeFilter GROUP BY time(1s), \"type_instance\" fill(linear)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" },
      { "condition": "AND", "key": "type", "operator": "=", "value": "ps_state" }
     ]
    }
   ]
  },
  {
   "title": "$host Read IOPs",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 21 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "$tag_instance",
     "groupBy": [
      { "params": [ "instance" ], "type": "tag" }
     ],
     "measurement": "disk_read",
     "query": "SELECT mean(\"value\") FROM \"autogen\".\"processes_value\" WHERE (\"host\"  =~ /^$host$/ AND \"type\" = 'fork_rate') AND $timeFilter GROUP BY time(1s), \"type_instance\" fill(linear)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       { "params": [ "1s" ], "type": "derivative" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" },
      { "condition": "AND", "key": "type", "operator": "=", "value": "disk_ops" }
     ]
    }
   ]
  },
  {
   "title": "$host Write IOPs",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 21 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "$tag_instance",
     "groupBy": [
      { "params": [ "instance" ], "type": "tag" }
     ],
     "measurement": "disk_write",
     "query": "SELECT mean(\"value\") FROM \"autogen\".\"processes_value\" WHERE (\"host\"  =~ /^$host$/ AND \"type\" = 'fork_rate') AND $timeFilter GROUP BY time(1s), \"type_instance\" fill(linear)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       { "params": [ "1s" ], "type": "derivative" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" },
      { "condition": "AND", "key": "type", "operator": "=", "value": "disk_ops" }
     ]
    }
   ]
  },
  {
   "title": "$host Disk Usage",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 21 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "alias": "$tag_instance",
     "groupBy": [
      { "params": [ "instance" ], "type": "tag" }
     ],
     "measurement": "df_value",
     "query": "SELECT mean(\"value\") FROM \"autogen\".\"processes_value\" WHERE (\"host\"  =~ /^$host$/ AND \"type\" = 'fork_rate') AND $timeFilter GROUP BY time(1s), \"type_instance\" fill(linear)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" },
      { "condition": "AND", "key": "type", "operator": "=", "value": "percent_bytes" },
      { "condition": "AND", "key": "type_instance", "operator": "=", "value": "used" }
     ]
    }
   ]
  },
  {
   "title": "$host Network Traffic/sec",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 27 },
   "yaxes": [
    { "format": "bps" }
   ],
   "targets": [
    {
     "alias": "$tag_instance Rx",
     "groupBy": [
      { "params": [ "instance" ], "type": "tag" },
      { "params": [ "type" ], "type": "tag" }
     ],
     "measurement": "interface_rx",
     "query": "SELECT mean(\"value\") FROM \"autogen\".\"processes_value\" WHERE (\"host\"  =~ /^$host$/ AND \"type\" = 'fork_rate') AND $timeFilter GROUP BY time(1s), \"type_instance\" fill(linear)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       { "params": [ "1s" ], "type": "derivative" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" },
      { "condition": "AND", "key": "type", "operator": "=", "value": "if_octets" }
     ]
    },
    {
     "alias": "$tag_instance Tx",
     "groupBy": [
      { "params": [ "instance" ], "type": "tag" },
      { "params": [ "type" ], "type": "tag" }
     ],
     "measurement": "interface_tx",
     "query": "SELECT mean(\"value\") FROM \"autogen\".\"processes_value\" WHERE (\"host\"  =~ /^$host$/ AND \"type\" = 'fork_rate') AND $timeFilter GROUP BY time(1s), \"type_instance\" fill(linear)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       { "params": [ "1s" ], "type": "derivative" },
       { "params": [ "*-1" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" },
      { "condition": "AND", "key": "type", "operator": "=", "value": "if_octets" }
     ]
    }
   ]
  },
  {
   "title": "$host Network Errors/sec",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 27 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "alias": "$tag_instance Rx",
     "groupBy": [
      { "params": [ "instance" ], "type": "tag" },
      { "params": [ "type" ], "type": "tag" }
     ],
     "measurement": "interface_rx",
     "query": "SELECT mean(\"value\") FROM \"autogen\".\"processes_value\" WHERE (\"host\"  =~ /^$host$/ AND \"type\" = 'fork_rate') AND $timeFilter GROUP BY time(1s), \"type_instance\" fill(linear)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       { "params": [ "1s" ], "type": "derivative" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" },
      { "condition": "AND", "key": "type", "operator": "=", "value": "if_errors" }
     ]
    },
    {
     "alias": "$tag_instance Tx",
     "groupBy": [
      { "params": [ "instance" ], "type": "tag" },
      { "params": [ "type" ], "type": "tag" }
     ],
     "measurement": "interface_tx",
     "query": "SELECT mean(\"value\") FROM \"autogen\".\"processes_value\" WHERE (\"host\"  =~ /^$host$/ AND \"type\" = 'fork_rate') AND $timeFilter GROUP BY time(1s), \"type_instance\" fill(linear)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       { "params": [ "1s" ], "type": "derivative" },
       { "params": [ "*-1" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" },
      { "condition": "AND", "key": "type", "operator": "=", "value": "if_errors" }
     ]
    }
   ]
  },
  {
   "title": "$host Network Packets/sec",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 27 },
   "yaxes": [
    { "format": "pps" }
   ],
   "targets": [
    {
     "alias": "$tag_instance Rx",
     "groupBy": [
      { "params": [ "instance" ], "type": "tag" },
      { "params": [ "type" ], "type": "tag" }
     ],
     "measurement": "interface_rx",
     "query": "SELECT mean(\"value\") FROM \"autogen\".\"processes_value\" WHERE (\"host\"  =~ /^$host$/ AND \"type\" = 'fork_rate') AND $timeFilter GROUP BY time(1s), \"type_instance\" fill(linear)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       { "params": [ "1s" ], "type": "derivative" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" },
      { "condition": "AND", "key": "type", "operator": "=", "value": "if_packets" }
     ]
    },
    {
     "alias": "$tag_instance Tx",
     "groupBy": [
      { "params": [ "instance" ], "type": "tag" },
      { "params": [ "type" ], "type": "tag" }
     ],
     "measurement": "interface_tx",
     "query": "SELECT mean(\"value\") FROM \"autogen\".\"processes_value\" WHERE (\"host\"  =~ /^$host$/ AND \"type\" = 'fork_rate') AND $timeFilter GROUP BY time(1s), \"type_instance\" fill(linear)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       { "params": [ "1s" ], "type": "derivative" },
       { "params": [ "*-1" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" },
      { "condition": "AND", "key": "type", "operator": "=", "value": "if_packets" }
     ]
    }
   ]
  },
  {
   "title": "$host Temperatures",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 33 },
   "yaxes": [
    { "format": "celsius" }
   ],
   "targets": [
    {
     "alias": "$tag_instance",
     "groupBy": [
      { "params": [ "instance" ], "type": "tag" }
     ],
     "measurement": "thermal_value",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" },
      { "condition": "AND", "key": "value", "operator": ">", "value": "0" }
     ]
    }
   ]
  }
 ]
}